GraduationProject.MVC/Models/FacultyViewModel.cs
using GraduationProject.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GraduationProject.MVC.Models
{
    public class FacultyViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] logo { get; set; }
        public int UniversityId { get; set; }
        public List<Tansiq> Tansiq { get; set; }

    }
}

GraduationProject.MVC/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraduationProject.Data;
using GraduationProject.Data.Entities;

namespace GraduationProject.MVC.Controllers
{
    [RoutePrefix("Dashboard/Faculties")]
    [Route("{action=Index}")]
    public class FacultiesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Faculties
        public ActionResult Index()
        {
            var faculties = db.Faculties.Include(f => f.University);
            return View(faculties.ToList());
        }
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }


        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.Faculties where temp.Id == Id select temp.logo;
            byte[] cover = q.First();
            return cover;
        }


        // GET: Faculties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // GET: Faculties/Create
        public ActionResult Create()
        {
            ViewBag.UniversityId = new SelectList(db.Universities, "Id", "Name");
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                faculty.logo = ConvertToBytes(file);
                db.Faculties.Add(faculty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UniversityId = new SelectList(db.Universities, "Id", "Name", faculty.UniversityId);
            return View(faculty);
        }
        public byte[] ConvertToBytes(HttpPostedFileBase Logo)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(Logo.InputStream);
            imageBytes = reader.ReadBytes((int)Logo.ContentLength);
            return imageBytes;
        }

        // GET: Faculties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            ViewBag.UniversityId = new SelectList(db.Universities, "Id", "Name", faculty.UniversityId);
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,logo,searchAppearancesCount,UniversityId")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faculty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UniversityId = new SelectList(db.Universities, "Id", "Name", faculty.UniversityId);
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Faculty faculty = db.Faculties.Find(id);
            db.Faculties.Remove(faculty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("~/api/faculties/{id}")]
        public ActionResult getAllByUniversityId(int id)
        {
            var faculties = db.Faculties.Where(i => i.UniversityId == id).Select(i => new { i.Id, i.Name });
            return Json(faculties, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraduationProject.MVC/Views/Faculties/Create.cshtml
@model GraduationProject.Data.Entities.Faculty

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}


<div class="container container-md-fluid">


    <div class="row mt-2">


        @using (Html.BeginForm("Create", "Faculties", FormMethod.Post, new { enctype = "multipart/form-data", @class ="col-lg-8 offset-lg-2 col-md-12 offset-md-0" }))
        {
            @Html.AntiForgeryToken()

        <div class="form bg-light rounded-lg border p-3">
            <h4 class="text-center py-1 my-1">Add new Faculty</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.logo, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageData" id="ImageData" onchange="imageFileCheck(this);" />
                    @Html.ValidationMessageFor(model => model.logo)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UniversityId, "University", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UniversityId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UniversityId, "", new { @class = "text-danger" })
                </div>
            </div>

            <tansiq></tansiq>

            <!-- submit -->
            <div class="form-group row">
                <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
                    <input type="submit" value="Create" class="btn btn-lg btn-primary bg-clr-primary text-center w-100" />
                </div>
            </div>
        </div>
        }
        </div>
    </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
        @*<script type="text/javascript">
                function fileCheck(obj) {
                    var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
                    if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
                        alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
                    }
                }
            </script>*@

GraduationProject.MVC/Views/Faculties/Delete.cshtml
@model GraduationProject.Data.Entities.Faculty

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Faculty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.University.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.searchAppearancesCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.searchAppearancesCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GraduationProject.MVC/Views/Faculties/Details.cshtml
@model GraduationProject.Data.Entities.Faculty

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Faculty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.University.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.searchAppearancesCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.searchAppearancesCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GraduationProject.MVC/Views/Faculties/Edit.cshtml
@model GraduationProject.Data.Entities.Faculty

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Faculty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.searchAppearancesCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.searchAppearancesCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.searchAppearancesCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UniversityId, "UniversityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UniversityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UniversityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GraduationProject.MVC/Views/Faculties/Index.cshtml
@model IEnumerable<GraduationProject.Data.Entities.Faculty>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<div class="container">
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.logo)
                </th>
                <th>
                    University
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>

                <th>
                    Search Appearances
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
    <tr>
        <td>
            <img src="/Faculties/RetrieveImage/@item.Id" alt="" height=100 width=200 />

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.University.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.searchAppearancesCount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
        }

    </table>
</div>