GraduationProject.MVC/Controllers/UniversitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraduationProject.Data;
using GraduationProject.Data.Entities;

namespace GraduationProject.MVC.Controllers
{
    [RoutePrefix("Dashboard/Universities")]
    [Route("{action=Index}")]
    public class UniversitiesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Universities
        public ActionResult Index()
        {
            return View(db.Universities.ToList());
        }

        [Route("RetrieveImage/{id}")]
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.Universities where temp.Id == Id select temp.Logo;
            byte[] cover = q.First();
            return cover;
        }

        // GET: Universities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            } else
            {
                university.Views = university.Views + 1;
                db.SaveChanges();
            }
            return View(university);
        }

        // GET: Universities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Universities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(University university)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["ImageData"];

                if(file.ContentLength > 1)
                {
                    university.Logo = ConvertToBytes(file);
                }
                db.Universities.Add(university);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(university);
        }
       
        public byte[] ConvertToBytes(HttpPostedFileBase Logo)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(Logo.InputStream);
            imageBytes = reader.ReadBytes((int)Logo.ContentLength);
            return imageBytes;
        }

        // GET: Universities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // POST: Universities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Zipcode,Street,City,Governorate,Logo,Description,Views")] University university)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["LogoIncoming"];

                if (file.ContentLength > 1)
                {
                    university.Logo = ConvertToBytes(file);
                }
                db.Entry(university).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(university);
        }

        // GET: Universities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // POST: Universities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            University university = db.Universities.Find(id);
            db.Universities.Remove(university);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraduationProject.MVC/Views/Universities/Create.cshtml
@model GraduationProject.Data.Entities.University

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}


<div class="container container-md-fluid">


    <div class="row mt-2">



    @using (Html.BeginForm("Create", "Universities", FormMethod.Post, new { enctype = "multipart/form-data", @class="col-lg-8 offset-lg-2 col-md-12 offset-md-0" }))
    {
        @Html.AntiForgeryToken()

        <div class="form bg-light rounded-lg border p-3" >
            <h4 class="text-center py-1 my-1">Add New University</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Logo, new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
                    @Html.ValidationMessageFor(model => model.Logo)
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Governorate, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    <select id="Governorate" name="Governorate" class="form-control" GovernorateSelector></select>
                    @Html.ValidationMessageFor(model => model.Governorate, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2 col-sm-12 text-left" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
                    <input type="submit" value="Create" class="btn btn-lg btn-primary bg-clr-primary text-center w-100" />
                </div>
            </div>
        </div>

    }
    </div>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
        }
    }
</script>

GraduationProject.MVC/Views/Universities/Delete.cshtml
@model GraduationProject.Data.Entities.University

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>University</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Governorate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Governorate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GraduationProject.MVC/Views/Universities/Details.cshtml
@model GraduationProject.Data.Entities.University

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>University</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Governorate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Governorate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GraduationProject.MVC/Views/Universities/Edit.cshtml
@model GraduationProject.Data.Entities.University

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}

    <div class="container container-md-fluid">


        <div class="row mt-2">

            @using (Html.BeginForm("Edit", "Universities", FormMethod.Post, new { enctype = "multipart/form-data", @class = "col-lg-8 offset-lg-2 col-md-12 offset-md-0" }))
            {
                @Html.AntiForgeryToken()

            <div class="form bg-light rounded-lg border p-3">
                <h4 class="text-center py-1 my-1">Edit University</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                @if (Model.Logo != null)
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img OldLogo width="200" height="100" src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Logo, 0, Model.Logo.Length)" />

                            @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                            <button type="button" class="btn btn-primary bg-clr-primary" ChangeLogo>Change</button>
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label for="exampleFormControlFile1" class="control-label col-md-2">Upload a logo!</label>
                        <div class="col-md-10">
                            <input type="file" class="form-control-file" id="LogoUpload" LogoIncoming name="LogoIncoming">
                        </div>
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(model => model.Governorate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select id="Governorate" name="Governorate" class="form-control" GovernorateSelector value="@Model.Governorate"></select>
                        @Html.ValidationMessageFor(model => model.Governorate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
                        <input type="submit" value="Save" class="btn btn-lg btn-primary bg-clr-primary text-center w-100" />
                    </div>
                </div>
            </div>
            }
        
            </div>
        </div>
    <div class="row my-2">
            <div class="col text-center">
                @Html.ActionLink("Back to List", "Index", null,htmlAttributes: new { @class = "btn btn-sm btn-primary bg-clr-secondary" })
            </div>
    </div>

<script>
    let $buttonElt = $('button[ChangeLogo]');
    let $oldLogoElt = $('img[OldLogo]');
    $buttonElt.click(_ => {
        let newFormItem = $(`
                    <div class="col-md-10">
                        <input type="file" class="form-control-file" LogoIncoming id="LogoUpload" name="LogoIncoming">
                    </div>`);
        $oldLogoElt.hide();
        $buttonElt.hide();
        $oldLogoElt.parent().append(newFormItem);
        let $photoUploadButton = $('input[LogoIncoming]');
        $photoUploadButton.trigger('click');
    });
</script>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

GraduationProject.MVC/Views/Universities/Index.cshtml
@model IEnumerable<GraduationProject.Data.Entities.University>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Dashboard_Layout.cshtml";
}
   

<div class="container">
    <div class="row my-2">
        <div class="col-10" >
            <h2 class="clr-secondary"> Universities </h2>
        </div>
        <div class="col-2">
            <a href="@Url.Action("Create", "Universities")"  class="btn btn-lg btn-primary bg-clr-primary "> Create New</a>          
        </div>
        </div>

    <div>
        <table class="table">
            <thead class="thead-dark">

                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Logo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Zipcode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Street)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.City)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Governorate)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Views)
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr class="my-2">
                    <td class="font-3rem text-center clr-secondary bg-light p-0 lh-100px">
                        @if (item.Logo != null)
                        {
                            <img src="/Dashboard/Universities/RetrieveImage/@item.Id" alt="" height=100 width=200 />
                        }
                        else
                        {
                            <i class="fas fa-university clr-secondary"></i>
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Zipcode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Street)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Governorate)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Views)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                    </td>
                </tr>
            }

        </table>
    </div>
    </div>