GraduationProject.MVC/Controllers/CoursesController.cs
using GraduationProject.Data;
using GraduationProject.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GraduationProject.MVC.Controllers
{
    [RoutePrefix("Dashboard/Courses")]
    [Route("{action=Index}")]
    public class CoursesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // GET: Interests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Interests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name")] Courses course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Interests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Interests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(courses);
        }

        // GET: Interests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // POST: Interests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courses courses = db.Courses.Find(id);
            db.Courses.Remove(courses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpGet]
        [Route("~/api/courses")]
        public ActionResult getAll()
        {
            var courses = db.Courses.Select(i => new { i.Id, i.Name }).ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }


    }
}

GraduationProject.MVC/Controllers/DivisionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraduationProject.Data;
using GraduationProject.Data.Entities;

namespace GraduationProject.MVC.Controllers
{
    [RoutePrefix("Dashboard/Divisions")]
    [Route("{action=Index}")]
    public class DivisionController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Division
        public ActionResult Index()
        {
            var Division = db.Division.Include(d => d.Faculty);
            return View(Division.ToList());
        }

        // GET: Division/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Division.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // GET: Division/Create
        public ActionResult Create()
        {
            ViewBag.UniversityId = new SelectList(db.Universities, "Id", "Name");
            return View();
        }

        // POST: Division/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Division division , string Interests, string courses)
        {
            // adding interests from a string of ids
            var interest = Interests.Split(',');
            var InterestsL = new List<int>();
            foreach (var b in interest)
            {
                InterestsL.Add(Int32.Parse(b));
            }
            var lIntenerts = db.Interests.Where(i => InterestsL.Contains(i.Id));

            // adding courses from a string of ids
            var course = courses.Split(',');
            var coursesL = new List<int>();
            foreach(var b in course)
            {
                coursesL.Add(Int32.Parse(b));
            }
            var lCourses = db.Courses.Where(i => coursesL.Contains(i.Id));

            // saving the division to database
            db.Division.Add(division);
            db.SaveChanges();

            // add each interest to division
            foreach (var i in lIntenerts)
            {
                division.Interests.Add(i);
            }

            // add each course into division
            foreach(var i in lCourses)
            {
                division.Courses.Add(i);
            }

            // presist db changes
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET: Division/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Division.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Name", division.FacultyId);
            return View(division);
        }

        // POST: Division/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,ExtraInfo,Views,FacultyId")] Division division)
        {
            if (ModelState.IsValid)
            {
                db.Entry(division).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Name", division.FacultyId);
            return View(division);
        }

        // GET: Division/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Division.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // POST: Division/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Division division = db.Division.Find(id);
            db.Division.Remove(division);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GraduationProject.MVC/Controllers/InterestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GraduationProject.Data;
using GraduationProject.Data.Entities;

namespace GraduationProject.MVC.Controllers
{
    [RoutePrefix("Dashboard/Interests")]
    [Route("{action=Index}")]
    public class InterestsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Interests
        public ActionResult Index()
        {
            return View(db.Interests.ToList());
        }

        // GET: Interests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // GET: Interests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Interests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name")] Interest interest)
        {
            if (ModelState.IsValid)
            {
                db.Interests.Add(interest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(interest);
        }

        // GET: Interests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // POST: Interests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name")] Interest interest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(interest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(interest);
        }

        // GET: Interests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interest interest = db.Interests.Find(id);
            if (interest == null)
            {
                return HttpNotFound();
            }
            return View(interest);
        }

        // POST: Interests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interest interest = db.Interests.Find(id);
            db.Interests.Remove(interest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpGet]
        [Route("~/api/interests")]
        public ActionResult getAll()
        {
            var interests = db.Interests.Select(i => new { i.Id, i.name }).ToList();
            return Json(interests,JsonRequestBehavior.AllowGet);
        }
    }
}

GraduationProject.MVC/Controllers/SearchController.cs
using GraduationProject.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using GraduationProject.MVC.Models;
using GraduationProject.Data.Entities;
using GraduationProject.MVC.Services;

namespace GraduationProject.MVC.Controllers
{
    public class SearchController : Controller
    {
        private DatabaseContext db = new DatabaseContext();
        // GET: Search
        public ActionResult Index()
        {
        //    var userId = int.Parse(User.Identity.GetUserId());
            
        //    ViewBag.specialization = db.Students.Where(r=>r.Id== userId).Select(a=>a.SpecializationId);
            ViewBag.specializationId = new SelectList(db.Specializations, "Id", "Name");
           // ViewBag.GovernorateId = db.Universities.Select(a => a.Governorate);
            //    ViewBag.Governorate = db.Students.Where(a => a.Id == userId).Select(n => n.Governorate);
            return View();
        }

        [HttpPost]
        public ActionResult Result(int specializationId, double Startgrade, string iii = "", string Governorate = "" , double Fees = 0, string course = "")
        {
            var bb = iii.Split(',');
            var interstids = new List<int>();
            if (iii.Length > 0)
            {
                foreach (var b in bb)
                {

                    interstids.Add(Int32.Parse(b));
                }
            }
            var cc = course.Split(',');
            var courseids = new List<int>();
            if(course.Length > 0)
            {
                foreach (var c in cc)
                {

                    courseids.Add(Int32.Parse(c));
                }
            }
            var courseList = db.Courses.Where(r => courseids.Contains(r.Id)).ToList();
            var interestList = db.Interests.Where(a => interstids.Contains(a.Id)).ToList();

            var result = db.Tansiq.Where(a => a.SpecializationId == specializationId && a.Startgrade <= Startgrade).ToList();


            if(interestList.Count > 0)
            {
                result = result.Where(r => r.Division.Interests.Intersect(interestList).Any()).ToList();
            }

            if(courseList.Count > 0)
            {
                result = result.Where(n => n.Division.Courses.Intersect(courseList).Any()).ToList();
            }

            if(Governorate != "" && Governorate != null)
            {
                result = result.Where(n => n.Division.Faculty.University.Governorate == Governorate).ToList();
            }

            if(Fees > 0)
            {
                result = result.Where(n => n.Division.Fees >= Fees).ToList();
            }



            SearchHistory searchHistory = new SearchHistory()
            {
                Governorate = Governorate,
                SpecializationId = specializationId,
                Grade = Startgrade,
                Timestamp = DateTime.Now,
                Interests = interestList
            };
            db.SearchHistories.Add(searchHistory);
            db.SaveChanges();

            foreach (var x in result)
            {
                db.Recommendations.Add(new Recommendation { SearchHistoryId = searchHistory.Id, DivisionId = x.Division.Id });
            }
            db.SaveChanges();

            var recIds = db.Recommendations.Where(r => r.SearchHistoryId == searchHistory.Id).Select(r => r.Id).ToList();

            List<ResultViewModel> Results = RecommendationExtractorService.getRecommendationVMListByIdList(recIds);

            return View(Results);
        }
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.Universities where temp.Id == Id select temp.Logo;
            byte[] cover = q.First();
            return cover;
        }


    }
}

GraduationProject.MVC/Views/Shared/_Dashboard_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - Dashboard - COLEGER</title>

    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-tags-input.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/typeahead.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/fa.all.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/sb-admin.min.css")" />
    <script src="@Url.Content("~/Scripts/chart.js")"></script>

    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/popper.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/typeahead.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tags-input.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/fa.all.min.js")" type="text/javascript"></script>
</head>

<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <a class="navbar-brand mr-1" href="@Url.Action("Index", "Home")">COLLEGER</a>



        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0"></ul>

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Dashboard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Universities")">
                    <i class="fas fa-fw fa-school"></i>
                    <span>Universities</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Faculties")">
                    <i class="fas fa-fw fa-university"></i>
                    <span>Faculties</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Division")">
                    <i class="fas fa-fw fa-suitcase"></i>
                    <span>Divisions</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Interests")">
                    <i class="fas fa-fw fa-receipt"></i>
                    <span>Interests</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Courses")">
                    <i class="fas fa-fw fa-scroll"></i>
                    <span>Courses</span>
                </a>
            </li>

        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">
                <div>
                    @RenderBody()
                </div>

            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © COLLEGER 2019</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>


</body>
<script src="@Url.Content("~/Scripts/index.js")"></script>
<script src="@Url.Content("~/Scripts/sb-admin.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.easing.min.js")"></script>
</html>

GraduationProject.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="height:100% !important">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - COLLEGER</title>

    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-tags-input.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/typeahead.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/fa.all.min.css")" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/popper.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/typeahead.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tags-input.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/fa.all.min.js")" type="text/javascript"></script>
</head>
<body class="">
    <nav class="navbar navbar-expand-lg navbar-light bg-light nav-border">
        <img src="~/Images/logo-color.png" width="40" height="40" class="d-inline-block align-top" alt="">
        <a class="navbar-brand clr-primary m-0 p-0" href="@Url.Action("Index", "Home")"><strong>COLLEGER</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>

                @if (User.IsInRole("admin"))
                {

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Dashboard")">Dashboard<span class="sr-only">(current)</span></a>
                    </li>

                }
                <li class="nav-item">
                    <a class="nav-link clr-secondary" href="@Url.Action("Index", "Search")">Find me a college!<span class="sr-only">(current)</span></a>
                </li>
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="body-content">


        @RenderBody()


    </div>
    <footer class="text-light text-center text-capitalize bg-clr-primary footer mt-auto py-3">
        <p class="m-0 p-0">&copy; @DateTime.Now.Year - COLLEGER</p>
    </footer>
    <script src="@Url.Content("~/Scripts/index.js")"></script>
</body>
</html>